services:
  postgres:
    container_name: notae_postgres_test
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eng_management_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

  app:
    container_name: notae_app_test
    image: notate_app_test
    environment: 
      RAILS_ENV: test
      SECRET_KEY_BASE_DUMMY: 1
    ports:
      - 3000:3000


volumes:
  postgres_test_data:

