services:
  postgres:
    container_name: notae_postgres_test
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eng_management_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    container_name: notae_app_test
    image: notate_app_test:ci
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      /bin/bash -c "
      bundle exec rails db:migrate &&
      bundle exec rails server -b 0.0.0.0
      "
    environment: 
      SECRET_KEY_BASE_DUMMY: 1
      RAILS_ENV: test
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_PORT: 5432
    ports:
      - 3000:3000